version: 2

models:
  - name: dim_products
    columns:
      - name: PRODUCT_ID
        tests:
          - not_null
          - unique

  - name: fct_sales
    columns:
      - name: ORDER_ID
        tests:
          - not_null

      - name: NET_SALES_AMOUNT
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0"
